//
//  AppDelegate.swift
//  pH Calculator
//
//  Created by Tim Snow on 21/05/2015.
//  Copyright (c) 2015 Tim Snow. All rights reserved.
//
//  This file is largely as generated by Xcode
//


import Cocoa


@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    
    
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        // Insert code here to initialize your application
    }
    
    
    func applicationWillTerminate(aNotification: NSNotification) {
        // Insert code here to tear down your application
    }
    
    
    func applicationShouldTerminateAfterLastWindowClosed(sender: NSApplication) -> Bool {
        // To quit the program when the window is closed
        return true
    }
    
    
}